GuardabosquesUSB/login/urls.py
from django.conf.urls import patterns, url

from login import views

urlpatterns = patterns('',
    url(r'^$', views.login, name='login')
)

GuardabosquesUSB/GuardabosquesUSB/models.py
from django.contrib.auth.models import User
from django.forms import ModelForm
from django import forms
from django.db import models
from login.models import Estudiante
from datetime import datetime


class TipoActividad(models.Model):
    nombre = models.CharField(max_length = 200)

    def __unicode__(self):
        return self.nombre

class TipoActividadForm(ModelForm):
    class Meta:
        model = TipoActividad
        fields = ['nombre']

class Actividad(models.Model):

    ACTIVIDAD_CHOICES= (
        ('TV', 'Trabajo en vivero'),
        ('TC', 'Trabajo en campo'),
        ('JR', 'Jornada de reforestacion'),
        ('ER', 'Ecorrutas'),

    )

    HORAS_CHOICES= (
        (0, 'Esperando validacion'),
        (1, 'Horas Validadas'),
        (2, 'Horas  Rechazadas'),

    )

    HORAS_VALUES= (
        ('1',1),
        ('2',2),
        ('3',3),
        ('4',4),
        ('5',5),
        ('6',6),
        ('7',7),
        ('8',8),
        ('9',9),
        ('10',10),
        ('11',11),
        ('12',12),
    )

    horas        = models.PositiveIntegerField(choices=HORAS_VALUES)
    descripcion  = models.ForeignKey(TipoActividad)
    validado_nuevo     = models.IntegerField(default=0,choices=HORAS_CHOICES)
    estudiante   = models.ForeignKey('login.Estudiante')
    fecha        = models.DateTimeField(default=datetime.now())

class ActividadForm(ModelForm):
    class Meta:
        model = Actividad
        fields = ['horas', 'descripcion', 'fecha']

class ValidacionForm(ModelForm):
    class Meta:
        model = Actividad
        fields =  []

GuardabosquesUSB/templates/actividades.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <title>Registro de Actividades - Sistema Administrativo Guardabosques USB</title>
        <meta name="generator" content="Bootply" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <!--[if lt IE 9]>
          <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <link href="{% static 'css/font-awesome.min.css' %}" type="text/css" rel="stylesheet">

        <!-- CSS code from Bootply.com editor -->

        <link href="{% static 'css/main.css' %}" rel="stylesheet">

        <!-- JavaScript jQuery code from Bootply.com editor -->

        <script type='text/javascript'>
          $(document).ready(function() {
           });
        </script>

        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

        <script type='text/javascript' src="{% static 'js/bootstrap.min.js' %}"></script>

        <!-- DataTables CSS -->
        <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.2/css/jquery.dataTables.css">

        <!-- jQuery -->
        <script type="text/javascript" charset="utf8" src="//code.jquery.com/jquery-1.10.2.min.js"></script>

        <!-- DataTables -->
        <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.2/js/jquery.dataTables.js"></script>

        <script type="text/javascript" class="init">
          $(document).ready(function () {
              $('#table_id').DataTable( {
                language: {
                   url: '//cdn.datatables.net/plug-ins/725b2a2115b/i18n/Spanish.json'
                }
              });
          } );
        </script>
    </head>

    <!-- HTML code from Bootply.com editor -->

    <body>

        <header class="navbar navbar-bright navbar-fixed-top" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/main/home" class="navbar-brand">Inicio</a>
    </div>
    <nav class="collapse navbar-collapse" role="navigation">
      <ul class="nav navbar-nav">
        <li id="selected">
          <a href="#">Registro de Actividades</a>
        </li>
        <li>
          <a href="/main/calendario">Calendario</a>
        </li>
        <li>
          <a href="/main/horas">Horas Acumuladas</a>
        </li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <li class="dropdown">
          <a href="#" id="nbAcctDD" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user"></i>
            {% if request.user.first_name%}
              {{ request.user.first_name }}
            {% else %}
              {{ request.user.username }}
            {% endif %}
            <i class="icon-sort-down"></i></a>
              <ul class="dropdown-menu pull-right">
                <li id="change_drop"><a id="change" href="/main/actualizar">Mis Datos</a></li>
                <li id="log_out_drop"><a id="log_out" href="/accounts/logout/">Cerrar Sesión</a></li>
              </ul>
        </li>
      </ul>
    </nav>
  </div>
</header>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="panel">
        <div class="panel-body">
          <!--/stories-->
          <div class="column">
            <form action="{% url "GuardabosquesUSB.views.registroActividad" %}"> {% csrf_token %}
              <input id="registroAct" type="submit" value="Registrar Nueva Actividad" />
            </form>
            <br><br><br>
            <div> <!-- Div para las tablas con las actividades -->
              <table id="table_id" border="1" class="display">
                  <thead>
                      <tr>
                          <th>Descripción</th>
                          <th>Horas</th>
                          <th>Fecha</th>
                          <th>Estatus</th>
                      </tr>
                  </thead>
                  <tbody>
                      {% for activ in acts %}
                      <tr>
                          <td> {{ activ.descripcion }} </td>
                          <td> {{ activ.horas }} </td>
                          <td> {{ activ.fecha }} </td>

                          <td>{{ activ.get_validado_nuevo_display }}</td>
                      </tr>
                      {% endfor %}
                  </tbody>
              </table>
            </div>
          </div>
        </div>
      </div><!--/col-12-->
    </div>
  </div>
  <div>
</body>

    <footer style="position:absolute;left:0;bottom:0;width:100%;height:40px;">
        <p>
      <img src="/static/image/logo.png" height="40" width="40" style="
    margin-top: -15px;
           margin-left: 30px;">   Creado por DevLab USB
        </p>
    </footer>

</html>

GuardabosquesUSB/templates/base.html
{% load url from future %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
  </head>
  <body>
    {% block body %}

    {% if messages %}
    <div>
      <strong>Messages:</strong>
      <ul>
	{% for message in messages %}
	<li>{{message}}</li>
	{% endfor %}
      </ul>
    </div>
    {% endif %}

    <div>
      <strong>Menu:</strong>
      <ul>
	{% if user.is_authenticated %}
	<li><a href="{% url 'account_email' %}">Change E-mail</a></li>
	<li><a href="{% url 'account_logout' %}">Sign Out</a></li>
	{% else %}
	<li><a href="{% url 'account_login' %}">Sign In</a></li>
	<li><a href="{% url 'account_signup' %}">Sign Up</a></li>
	{% endif %}
      </ul>
    </div>
    {% block content %}
    {% endblock %}
    {% endblock %}
    {% block extra_body %}
    {% endblock %}
  </body>
</html>

GuardabosquesUSB/templates/calendario.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <title>Calendario - Sistema Administrativo Guardabosques USB</title>
        <meta name="generator" content="Bootply" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <!--[if lt IE 9]>
          <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <link href="{% static 'css/font-awesome.min.css' %}" type="text/css" rel="stylesheet">
        <script type="text/javascript" src="https://www.google.com/jsapi"></script>
        <link href="{% static 'css/main.css' %}" rel="stylesheet">
    </head>

    <body>

        <header class="navbar navbar-bright navbar-fixed-top" role="banner">
            <div class="container">
              <div class="navbar-header">
                <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a href="/main/home" class="navbar-brand">Inicio</a>
              </div>
              <nav class="collapse navbar-collapse" role="navigation">
                                <ul class="nav navbar-nav">
                {% if admin %}
                  <li>
                    <a href="/main/validacion">Validación de Horas</a>
                  </li>
                  <li>
                      <a href ="/main/actividades/registroTipoActividad">Crear Actividad</a>
                  </li>
                  <li id="selected">
                    <a href="#">Calendario</a>
                  </li>
                  <li class="dropdown">
                    <a href="#" id="nbAcctDD" class="dropdown-toggle" data-toggle="dropdown">Información de los Estudiantes</a><i class="icon-user"></i>
                    <i class="icon-sort-down"></i></a>
                    <ul class="dropdown-menu pull-right">
                        <li id="change_drop"><a id="change" href="/main/mostrarEstudiantesRestantes">Activos</a></li>
                        <li id="log_out_drop"><a id="log_out" href="/main/mostrarEstudiantesFinalizados">Finalizados</a></li>
                    </ul>
                  </li>
                {% else %}
                  <li>
                    <a href="/main/actividades">Registro de Actividades</a>
                  </li>
                  <li id="selected">
                    <a href="#">Calendario</a>
                  </li>
                  <li>
                    <a href="/main/horas">Horas Acumuladas</a>
                  </li>
                {% endif %}
                </ul>
                <ul class="nav navbar-nav pull-right">
                  <li class="dropdown">
                    <a href="#" id="nbAcctDD" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user"></i>
                      {% if request.user.first_name%}
                        {{ request.user.first_name }}
                      {% else %}
                        {{ request.user.username }}
                      {% endif %}
                      <i class="icon-sort-down"></i></a>
                        {% if admin %}
                        <ul class="dropdown-menu pull-right">
                          <li id="log_out_drop"><a id="log_out" href="/accounts/logout/">Cerrar Sesión</a></li>
                        </ul>
                        {% else %}
                        <ul class="dropdown-menu pull-right">
                          <li id="change_drop"><a id="change" href="/main/actualizar">Mis Datos</a></li>
                          <li id="log_out_drop"><a id="log_out" href="/accounts/logout/">Cerrar Sesión</a></li>
                        </ul>
                        {% endif %}
                  </li>
                </ul>
              </nav>
            </div>
        </header>

        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <div class="panel">
                <div class="panel-body">
                  <!--/stories-->
                  <div class="column" style="text-align:center">
                    <p>
                      Visualice los eventos próximos en los cuales podrá participar.
                    </p>
                    <br>
                        <iframe id="calendario" style="border: 0" width="1000" height="500" frameborder="0" scrolling="no"></iframe>
                        <script type="text/javascript">
                          var correo = 'https://www.google.com/calendar/embed?src=app.guardabosques@gmail.com';
                          document.getElementById("calendario").src = correo;
                        </script>
                        <hr>
                  </div>
                </div>
              </div>
            </div><!--/col-12-->
          </div>
        </div>
        <hr>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script type='text/javascript' src="{% static 'js/bootstrap.min.js' %}"></script>

        <!-- JavaScript jQuery code from Bootply.com editor -->

        <script type='text/javascript'>

        $(document).ready(function() {



        });

        </script>

    </body>

    <footer style="position:absolute;left:0;bottom:0;width:100%;height:40px;">
        <p>
      <img src="/static/image/logo.png" height="40" width="40" style="
    margin-top: -15px;
           margin-left: 30px;">   Creado por DevLab USB
        </p>
    </footer>
</html>

GuardabosquesUSB/templates/crearTipoActividad.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <title>Registro de Actividades - Sistema Administrativo Guardabosques USB</title>
        <meta name="generator" content="Bootply" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <!--[if lt IE 9]>
          <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <link href="{% static 'css/font-awesome.min.css' %}" type="text/css" rel="stylesheet">

        <script type="text/javascript" src="https://www.google.com/jsapi"></script>

        <!-- CSS code from Bootply.com editor -->

        <link href="{% static 'css/main.css' %}" rel="stylesheet">

        <!-- JavaScript jQuery code from Bootply.com editor -->

        <script type='text/javascript'>
          $(document).ready(function() {
           });
        </script>

        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

        <script type='text/javascript' src="{% static 'js/bootstrap.min.js' %}"></script>

        <!-- DataTables CSS -->
        <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.2/css/jquery.dataTables.css">

        <!-- jQuery -->
        <script type="text/javascript" charset="utf8" src="//code.jquery.com/jquery-1.10.2.min.js"></script>

        <!-- DataTables -->
        <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.2/js/jquery.dataTables.js"></script>

        <script type="text/javascript" class="init">
          $(document).ready(function () {
              $('#table_id').DataTable( {
                language: {
                   url: '//cdn.datatables.net/plug-ins/725b2a2115b/i18n/Spanish.json'
                }
              });
          } );
        </script>
    </head>

    <!-- HTML code from Bootply.com editor -->

    <body>

        <header class="navbar navbar-bright navbar-fixed-top" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/main/home" class="navbar-brand">Inicio</a>
    </div>
    <nav class="collapse navbar-collapse" role="navigation">
      <ul class="nav navbar-nav">
        <li>
          <a href="/main/validacion">Validación de Horas</a>
        </li>
        <li id="selected">
            <a href ="#">Crear Actividad</a>
        </li>
        <li>
          <a href="/main/calendario">Calendario</a>
        </li>
        <li class="dropdown">
          <a href="#" id="nbAcctDD" class="dropdown-toggle" data-toggle="dropdown">Información de los Estudiantes</a><i class="icon-user"></i>
          <i class="icon-sort-down"></i></a>
          <ul class="dropdown-menu pull-right">
              <li id="change_drop"><a id="change" href="/main/mostrarEstudiantesRestantes">Activos</a></li>
              <li id="log_out_drop"><a id="log_out" href="/main/mostrarEstudiantesFinalizados">Finalizados</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <li class="dropdown">
          <a href="#" id="nbAcctDD" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user"></i>
            {% if request.user.first_name%}
              {{ request.user.first_name }}
            {% else %}
              {{ request.user.username }}
            {% endif %}
            <i class="icon-sort-down"></i></a>
              <ul class="dropdown-menu pull-right">
                <li id="log_out_drop"><a id="log_out" href="/accounts/logout/">Cerrar Sesión</a></li>
              </ul>
        </li>
      </ul>
    </nav>
  </div>
</header>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="panel">
        <div class="panel-body">
            <br></br>
          <div class="column" style="text-align:center">
            <p>
              Agregue las nuevas actividades para que los estudiantes suban sus horas.
            </p>
          </div>
          <div class-"column">
            <br><br>
            <form action="{% url "registroTipoActividad" %}" method="post">{% csrf_token %}
                {{ form.as_p }}
                <input  id="registroAct" type="submit" value="Registrar" />
            </form>
            <div class="column">
                 <!-- aqui -->
            <br>
            <table id="table_id" border="1" class="display">
                <thead>
                    <tr>
                        <th style="text-align:center">Actividad</th>
                        <th style="text-align:center">Eliminar</th>
                    </tr>
                </thead>
                <tbody>
                  {% for cest in actividades %}

                  <tr>
                      <td> {{ cest }} </td>
                      <td style="padding: 5px">

                <form method="post" action="{% url 'borrarTipoActividad' cest.pk %}">{% csrf_token %}<input type="submit" name="submit" value="Eliminar"></form>
                      </td>
                  </tr>
                    {% endfor %}
                </tbody>
            </table>
            </div>
          </div>
      </div><!--/col-12-->
    </div>
  </div>
</div>

</body>

    <footer style="position:absolute;left:0;bottom:0;width:100%;height:40px;">
        <p>
      <img src="/static/image/logo.png" height="40" width="40" style="
    margin-top: -15px;
           margin-left: 30px;">   Creado por DevLab USB
        </p>
    </footer>

</html>

GuardabosquesUSB/templates/horasAcumuladas.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <title>Horas Acumuladas - Sistema Administrativo Guardabosques USB</title>
  <meta name="generator" content="Bootply" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <!--[if lt IE 9]>
          <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
          <![endif]-->
          <link href="{% static 'css/font-awesome.min.css' %}" type="text/css" rel="stylesheet">
          <script type="text/javascript" src="https://www.google.com/jsapi"></script>
          <script type="text/javascript">
          google.load("visualization", "1", {packages:["corechart"]});
          google.setOnLoadCallback(drawChart);
          function drawChart() {
            var resto = 120 - {{ horas }}
            var data = google.visualization.arrayToDataTable([
              ['Task', 'Horas completadas'],
              ['Completadas',     {{ horas }}],
              ['Restantes',     resto]
              ]);

            var options = {
              title: 'Mis Horas',
              legend: 'none'
            };

            var chart = new google.visualization.PieChart(document.getElementById('piechart'));
            chart.draw(data, options);
          }
  </script>
  <link href="{% static 'css/main.css' %}" rel="stylesheet">

  <!-- JavaScript jQuery code from Bootply.com editor -->

  <script type='text/javascript'>
  $(document).ready(function() {
  });
  </script>

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

  <script type='text/javascript' src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- DataTables CSS -->
  <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.2/css/jquery.dataTables.css">

  <!-- jQuery -->
  <script type="text/javascript" charset="utf8" src="//code.jquery.com/jquery-1.10.2.min.js"></script>

  <!-- DataTables -->
  <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.2/js/jquery.dataTables.js"></script>

  <script type="text/javascript" class="init">
  $(document).ready(function () {
    $('#table_id').DataTable( {
      language: {
       url: '//cdn.datatables.net/plug-ins/725b2a2115b/i18n/Spanish.json'
     }
   });
  } );
  </script>
  
</head>

<body>

  <header class="navbar navbar-bright navbar-fixed-top" role="banner">
    <div class="container">
      <div class="navbar-header">
        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="/main/home" class="navbar-brand">Inicio</a>
      </div>
      <nav class="collapse navbar-collapse" role="navigation">
        <ul class="nav navbar-nav">
          <li>
            <a href="/main/actividades">Registro de Actividades</a>
          </li>
          <li>
            <a href="/main/calendario">Calendario</a>
          </li>
          <li id="selected">
            <a href="#">Horas Acumuladas</a>
          </li>
        </ul>
        <ul class="nav navbar-nav pull-right">
          <li class="dropdown">
            <a href="#" id="nbAcctDD" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user"></i>
              {% if request.user.first_name%}
              {{ request.user.first_name }}
              {% else %}
              {{ request.user.username }}
              {% endif %}
              <i class="icon-sort-down"></i></a>
              <ul class="dropdown-menu pull-right">
                <li id="change_drop"><a id="change" href="/main/actualizar">Mis Datos</a></li>
                <li id="log_out_drop"><a id="log_out" href="/accounts/logout/">Cerrar Sesión</a></li>
              </ul>
            </li>
          </ul>
        </nav>
      </div>
    </header>

    <div class="container" id="main">
      <div class="row">
        <div class="col-md-12">
          <div class="panel">
            <div class="panel-body">
              <div class="column" style="text-align:center">
                <p>
                  Visualice las horas validadas que ha realizado durante el Servicio, y su porcentaje de completación.
                </p>
                <br>
                <table id="table_id" border="1" class="display">
                  <thead>
                    <tr>
                      <th style="text-align:center">Descripción</th>
                      <th style="text-align:center">Horas realizadas</th>
                      <th style="text-align:center">Fecha</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for act in actividades %}
                    <tr>
                      <td> {{ act.0 }} </td>
                      <td> {{ act.1 }} </td>
                      <td> {{ act.2 }} </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
                <hr>
                <div id="piechart" style="width: 400px; height: 400px;"></div>
              </div>
            </div>
          </div><!--/col-12-->
        </div>
      </div>
      <footer>
        <p>
          <img src="/static/image/logo.png" height="40" width="40" style="
          margin-top: -15px;
          margin-left: 30px;">   Creado por DevLab USB
        </p>
      </footer>
    </div>

</body>


</html>

GuardabosquesUSB/templates/reportePdf.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <title>Reporte PDF - Sistema Administrativo Guardabosques USB</title>
        <meta name="generator" content="Bootply" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <style type="text/css">
            @page {
                size: {{ pagesize }};
                margin: 1cm;
                @frame footer {
                    -pdf-frame-content: footerContent;
                    bottom: 0cm;
                    margin-left: 9cm;
                    margin-right: 9cm;
                    height: 1cm;
                }
            }
        </style>
        <!--[if lt IE 9]>
          <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <link href="{% static 'css/font-awesome.min.css' %}" type="text/css" rel="stylesheet">

        <!-- CSS code from Bootply.com editor -->

        <link href="{% static 'css/main.css' %}" rel="stylesheet">

        <!-- JavaScript jQuery code from Bootply.com editor -->

        <script type='text/javascript'>
          $(document).ready(function() {
           });
        </script>

        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

        <script type='text/javascript' src="{% static 'js/bootstrap.min.js' %}"></script>

        <!-- DataTables CSS -->
        <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.2/css/jquery.dataTables.css">

        <!-- jQuery -->
        <script type="text/javascript" charset="utf8" src="//code.jquery.com/jquery-1.10.2.min.js"></script>

        <!-- DataTables -->
        <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.2/js/jquery.dataTables.js"></script>

        <script type="text/javascript" class="init">
          $(document).ready(function () {
              $('#table_id').DataTable( {
                searching: false,
                paging : false,
                language: {
                   url: '//cdn.datatables.net/plug-ins/725b2a2115b/i18n/Spanish.json'
                }
              });
          } );
        </script>
    </head>

    <!-- HTML code from Bootply.com editor -->

    <body>

<div class="container">
  <h1>Guardabosques de la Universidad Simón Bolívar</h1>
  <h1>Reporte de actividades</h1>
  <div class="row">
    <div class="col-md-12">
      <div class="panel">
        <div class="panel-body">
          <!--/stories-->
          <div class="column">
            <div> <!-- Div para las tablas con las actividades -->
              <table id="table_id" border="1" class="display" style="text:center">
                  <thead>
                      <tr>
                          <th>Descripción</th>
                          <th>Horas</th>
                          <th>Fecha</th>
                          <th>Estatus</th>
                      </tr>
                  </thead>
                  <tbody style="text-align:center;">
                      {% for activ in acts %}
                      <tr>
                          <td> {{ activ.descripcion }} </td>
                          <td> {{ activ.horas }} </td>
                          <td> {{ activ.fecha }} </td>

                          <td>{{ activ.get_validado_nuevo_display }}</td>
                      </tr>
                      {% endfor %}
                  </tbody>
              </table>
            </div>
          </div>
        </div>
      </div><!--/col-12-->
    </div>
  </div>
  <div>
</body>

</html>